### ISSUE TITLE
Support for mediatr 10

### ISSUE THREAD

**Issue by steveoh** [AustinDavies/MediatR.Behaviors.Authorization#7]
I upgraded to mediatr 10.0.1 and this was thrown from `AddMediatorAuthorization`

```cs
Unhandled exception. System.TypeLoadException: Could not load type 'MediatR.IRequest`1' from assembly 'MediatR, Version=10.0.0.0, Culture=neutral, PublicKeyToken=bb9a41a5e8aaa7e2'.
   at MediatR.Behaviors.Authorization.Extensions.DependencyInjection.AddMediatorAuthorizationExtension.AddMediatorAuthorization(IServiceCollection services, Assembly assembly)
   at api.Startup.ConfigureServices(IServiceCollection services) in Startup.cs:line 37
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at api.Program.Main(String[] args) in Program.cs:line 10
```

**Comment by steveoh** [comment]
i like that you changed the versioning scheme! 💫
